doctrine:
    dbal:
        default_connection: default
        url: '%env(resolve:DATABASE_URL)%'
        types:
            # Survey
            SurveyId: SurveySystem\Survey\Infrastructure\Persistence\Doctrine\Survey\DoctrineSurveyId

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                auto_mapping: true
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Survey:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Survey/Infrastructure/Persistence/Doctrine/Survey'
                        prefix: 'SurveySystem\Survey\Domain\Survey'
                        alias: Survey
                    SurveyQuestion:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Survey/Infrastructure/Persistence/Doctrine/SurveyQuestion'
                        prefix: 'SurveySystem\Survey\Domain\SurveyQuestion'
                        alias: SurveyQuestion

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
