SurveySystem\Survey\Domain\Report\DailyReport:
  shortName: 'DailyReport'
  description: 'Resource'
  iri: 'https://schema.org/DailyReport'
  attributes: []
  collectionOperations:

    get_daily_report_list:
      method: 'GET'
      path: '/daily-report'
      schemes: [ 'https', 'http' ]
      controller: SurveySystem\Apps\Api\Controller\Report\Daily\GetDailyReportListController
      defaults:
        _api_receive: false
      openapi_context:
        summary: 'Get Daily Report list'
        description: ''
        parameters:
          - in: query
            name: surveyId
            required: true
            schema:
              type: string
          - in: query
            name: initDate
            required: true
            schema:
              type: string
          - in: query
            name: endDate
            required: true
            schema:
              type: string
        responses:
          200:
            description: 'Daily Report list'

  itemOperations: []
