SurveySystem\Survey\Domain\Survey\Survey:
  shortName: 'Survey'
  description: 'Resource'
  iri: 'https://schema.org/Survey'
  attributes: []
  collectionOperations:

    get_survey_list:
      method: 'GET'
      path: '/surveys'
      schemes: [ 'https', 'http' ]
      controller: SurveySystem\Apps\Api\Controller\Survey\GetSurveyListController
      defaults:
        _api_receive: false
      swagger_context:
        summary: 'Get Surveys list'
        description: ''
        parameters: [ ]
        responses:
          200:
            description: 'Surveys list'

  itemOperations:

    get_survey_detail:
      method: 'GET'
      path: '/survey/{id}'
      schemes: [ 'https', 'http' ]
      controller: SurveySystem\Apps\Api\Controller\Survey\GetSurveyDetailByIdController
      defaults:
        _api_receive: false
      swagger_context:
        summary: 'Get Survey detail by id'
        description: ''
        parameters: []
        responses:
          200:
            description: 'Survey detail'
          400:
            description: 'Incorrect Parameters'
